# Generated by Django 5.0.3 on 2024-03-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=20)),
                ('company_address', models.CharField(max_length=20)),
                ('about_company', models.CharField(max_length=50)),
                ('number_of_employee', models.IntegerField()),
                ('company_ceo', models.CharField(max_length=20)),
                ('work_mode', models.CharField(choices=[('WFH', 'Work From Home'), ('WFO', 'Work From Office')], max_length=10)),
            ],
        ),
    ]
